version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - redis
      - rabbitmq      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  postgres:    
    image: postgres
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      TZ: Europe/Istanbul
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"   
    ports:
      - "15672:15672"
      - "5672:5672"