version: '3'
services:
  web:
    build: .
    ports:
        - "8000:80"
    depends_on:
        - redis
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"